package learn.exception;

public class InnerThrow {

    public void tetst() {
        System.out.println("test开始");

        int x = 1/ 0;

        System.out.println("test结束");
    }
}
